### ISSUE TITLE
babel-env is deprecated

### ISSUE THREAD

**Issue by northwood-dev** [symfony/stimulus-testing#7]
In the readme we have this ` "presets": ["@babel/env"]` line but the [package is deprecated](https://www.npmjs.com/package/babel-env).   Should we use [@babel/preset-env](https://babeljs.io/docs/babel-preset-env) insted ?

**Comment by weaverryan** [comment]
Definitely! In fact, the paragraph above we say `@babel/preset-env`, but the code block is wrong. Can you open a pull request to change that?
